import { FoodItem, ExerciseItem, Goal } from "./types";

export const DEFAULT_GOAL: Goal = {
  calories: 2000,
  protein: 130, // in grams (typical for active/healthy goals)
  carbs: 220,   // in grams
  fat: 65,      // in grams
};

export const COMMON_FOOD_ITEMS: FoodItem[] = [
  {
    id: "f1",
    name: "Grilled Chicken Breast",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f2",
    name: "Whole Large Egg",
    calories: 70,
    protein: 6,
    carbs: 0.6,
    fat: 5,
    servingSize: 1,
    servingUnit: "egg",
  },
  {
    id: "f3",
    name: "White Rice (Cooked)",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f4",
    name: "Brown Rice (Cooked)",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f5",
    name: "Oatmeal (Cooked in Water)",
    calories: 71,
    protein: 2.5,
    carbs: 12,
    fat: 1.4,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f6",
    name: "Whey Protein Shake",
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
    servingSize: 1,
    servingUnit: "scoop",
  },
  {
    id: "f7",
    name: "Peanut Butter (Smooth)",
    calories: 94,
    protein: 4,
    carbs: 3,
    fat: 8,
    servingSize: 16,
    servingUnit: "g (1 tbsp)",
  },
  {
    id: "f8",
    name: "Fresh Banana",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.3,
    servingSize: 1,
    servingUnit: "medium banana",
  },
  {
    id: "f9",
    name: "Avocado",
    calories: 240,
    protein: 3,
    carbs: 12,
    fat: 22,
    servingSize: 1,
    servingUnit: "medium avocado",
  },
  {
    id: "f10",
    name: "Sweet Potato (Baked)",
    calories: 90,
    protein: 2,
    carbs: 21,
    fat: 0.2,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f11",
    name: "Salmon Fillet (Baked)",
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 12,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f12",
    name: "Greek Yogurt (0% Plain)",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f13",
    name: "Almonds (Raw)",
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    servingSize: 28,
    servingUnit: "g (1 oz)",
  },
  {
    id: "f14",
    name: "Broccoli (Steamed)",
    calories: 35,
    protein: 2.4,
    carbs: 7,
    fat: 0.4,
    servingSize: 100,
    servingUnit: "g",
  },
  {
    id: "f15",
    name: "Whole Milk",
    calories: 149,
    protein: 8,
    carbs: 12,
    fat: 8,
    servingSize: 244,
    servingUnit: "ml (1 cup)",
  }
];

export const PRESET_EXERCISES: ExerciseItem[] = [
  { id: "e1", name: "Running (Moderate Pace)", caloriesPerMinute: 11.4 },
  { id: "e2", name: "Cycling (Leisurely)", caloriesPerMinute: 7.5 },
  { id: "e3", name: "Cycling (Vigorous)", caloriesPerMinute: 12.0 },
  { id: "e4", name: "Swimming (General)", caloriesPerMinute: 9.8 },
  { id: "e5", name: "Weight Lifting (Intensity)", caloriesPerMinute: 6.0 },
  { id: "e6", name: "Walking (Brisk Pace)", caloriesPerMinute: 4.5 },
  { id: "e7", name: "HIIT Workout", caloriesPerMinute: 13.5 },
  { id: "e8", name: "Yoga", caloriesPerMinute: 3.2 },
  { id: "e9", name: "Rowing Machine", caloriesPerMinute: 8.5 },
];

export const SAMPLE_BARCODES = [
  { barcode: "070569005077", name: "Rolled Oats", brand: "Quaker" },
  { barcode: "011110038364", name: "Greek Yogurt", brand: "Kroger" },
  { barcode: "021130070519", name: "Whole Wheat Bread", brand: "Lucerne" },
  { barcode: "074570610053", name: "Whey Protein", brand: "Gold Standard" },
  { barcode: "49000000443", name: "Coca-Cola Classic", brand: "Coca-Cola" }
];
